import { sql } from 'drizzle-orm'
import type { Db } from '@athlos/db'
import { BusinessError, ErrorCode } from '@athlos/errors'
import type { DuesTransaction } from './repository.ts'

export type DuesDb = Db | DuesTransaction
type Json = Record<string, unknown>
export const MAX_MONEY_CENTS = 99_999_999_999_999
// prettier-ignore
export type SettlementKind = 'MONETARY' | 'NON_CASH';
export type AllocationKind = 'ALLOCATION' | 'COMPENSATION'
// prettier-ignore
export type SettlementInput = { operatorId:string; socioId:string; kind:SettlementKind; amountCents:number; currency:string; evidence:Json; reason?:string; reversalOfSettlementId?:string|null; callerKey:string; requestFingerprint:string; authorizationEvidence:Json }
// prettier-ignore
export type AllocationInput = { settlementId:string; socioId:string; obligationId:string; amountCents:number; kind?:AllocationKind; compensatesAllocationId?:string; reason?:string }
// prettier-ignore
export type SettlementRecord = { id:string; socioId:string; kind:SettlementKind; amountCents:number; currency:string; reversalOfSettlementId:string|null }
// prettier-ignore
export type AllocationRecord = { id:string; settlementId:string; obligationId:string; kind:AllocationKind; amountCents:number; compensatesAllocationId:string|null }
// prettier-ignore
export type SettlementClaim = { status:'claimed'; settlement:SettlementRecord } | { status:'replayed'; settlement:SettlementRecord; allocations:AllocationRecord[] }
const rows = <T>(value: unknown) => (value as { rows?: T[] }).rows ?? []
const money = (cents: number) => (cents / 100).toFixed(2)
const cents = (amount: string) => {
  const [whole, fraction = ''] = amount.split('.')
  return Number(whole) * 100 + Number((fraction + '00').slice(0, 2))
}
// prettier-ignore
export function allocationTotal(items:Array<{ obligationId:string; amountCents:number }>):number { const seen = new Set<string>(); const total = items.reduce((sum, item) => { if (seen.has(item.obligationId) || !Number.isSafeInteger(item.amountCents) || item.amountCents <= 0 || item.amountCents > MAX_MONEY_CENTS) throw BusinessError(ErrorCode.VALIDATION_ERROR, 'Allocations must contain unique positive amounts within the supported money range'); seen.add(item.obligationId); return sum + item.amountCents }, 0); if (!Number.isSafeInteger(total) || total <= 0 || total > MAX_MONEY_CENTS) throw BusinessError(ErrorCode.VALIDATION_ERROR, 'At least one allocation is required within the supported money range'); return total }
// prettier-ignore
const settlement = (row:{id:string;socioId:string;kind:SettlementKind;amount:string;currency:string;reversalOfSettlementId:string|null}):SettlementRecord => ({ id:row.id, socioId:row.socioId, kind:row.kind, amountCents:cents(row.amount), currency:row.currency, reversalOfSettlementId:row.reversalOfSettlementId })
// prettier-ignore
const allocation = (row:{id:string;settlementId:string;obligationId:string;kind:AllocationKind;amount:string;compensatesAllocationId:string|null}):AllocationRecord => ({ id:row.id, settlementId:row.settlementId, obligationId:row.obligationId, kind:row.kind, amountCents:cents(row.amount), compensatesAllocationId:row.compensatesAllocationId })
const settlementFields = sql`id, socio_id AS "socioId", kind, amount::text, btrim(currency) AS currency, reversal_of_settlement_id AS "reversalOfSettlementId"`
const allocationFields = sql`id, settlement_id AS "settlementId", obligation_id AS "obligationId", kind, amount::text, compensates_allocation_id AS "compensatesAllocationId"`
// prettier-ignore
export async function listAllocations(db:DuesDb, settlementId:string):Promise<AllocationRecord[]> { return rows<Parameters<typeof allocation>[0]>(await db.execute(sql`SELECT ${allocationFields} FROM tesoreria.dues_allocations WHERE settlement_id = ${settlementId} ORDER BY created_at, id`)).map(allocation) }
// prettier-ignore
export async function claimSettlement(db:DuesDb, input:SettlementInput):Promise<SettlementClaim> { const inserted = rows<Parameters<typeof settlement>[0]>(await db.execute(sql`INSERT INTO tesoreria.dues_settlements (socio_id,kind,amount,currency,evidence,reason,reversal_of_settlement_id,operator_id,authorization_evidence,caller_key,request_fingerprint) VALUES (${input.socioId},${input.kind},${money(input.amountCents)},${input.currency},${JSON.stringify(input.evidence)}::jsonb,${input.reason ?? null},${input.reversalOfSettlementId ?? null},${input.operatorId},${JSON.stringify(input.authorizationEvidence)}::jsonb,${input.callerKey},${input.requestFingerprint}) ON CONFLICT (operator_id,caller_key) DO NOTHING RETURNING ${settlementFields}`))[0]; if (inserted) return { status:'claimed', settlement:settlement(inserted) }; const existing = rows<Parameters<typeof settlement>[0]>(await db.execute(sql`SELECT ${settlementFields} FROM tesoreria.dues_settlements WHERE operator_id = ${input.operatorId} AND caller_key = ${input.callerKey}`))[0]; if (!existing) throw BusinessError(ErrorCode.SERVICE_UNAVAILABLE, 'Settlement claim is unavailable'); const fingerprint = rows<{requestFingerprint:string}>(await db.execute(sql`SELECT request_fingerprint AS "requestFingerprint" FROM tesoreria.dues_settlements WHERE id = ${existing.id}`))[0]?.requestFingerprint; if (fingerprint !== input.requestFingerprint) throw BusinessError(ErrorCode.CONFLICT, 'Idempotency key was already used for a different settlement'); return { status:'replayed', settlement:settlement(existing), allocations:await listAllocations(db, existing.id) } }
// prettier-ignore
export async function insertAllocation(db:DuesDb, input:AllocationInput):Promise<AllocationRecord> { const kind = input.kind ?? 'ALLOCATION'; const s = rows<{socioId:string;amount:string}>(await db.execute(sql`SELECT socio_id AS "socioId", amount::text FROM tesoreria.dues_settlements WHERE id = ${input.settlementId}`))[0]; const o = rows<{id:string;socioId:string;amount:string}>(await db.execute(sql`SELECT id,socio_id AS "socioId",amount::text FROM tesoreria.dues_obligations WHERE id = ${input.obligationId} FOR UPDATE`))[0]; if (!s || !o) throw BusinessError(ErrorCode.NOT_FOUND, 'Settlement or obligation not found'); if (s.socioId !== input.socioId || o.socioId !== input.socioId) throw BusinessError(ErrorCode.CONFLICT, 'Settlement and obligation member do not match'); if (kind === 'COMPENSATION') { const original = rows<{obligationId:string;amount:string}>(await db.execute(sql`SELECT obligation_id AS "obligationId",amount::text FROM tesoreria.dues_allocations WHERE id = ${input.compensatesAllocationId}`))[0]; if (!original || original.obligationId !== input.obligationId || cents(original.amount) !== input.amountCents) throw BusinessError(ErrorCode.VALIDATION_ERROR, 'Compensation must restore the original allocation') } else { const outstanding = rows<{amount:string}>(await db.execute(sql`SELECT (${o.amount}::numeric - COALESCE(SUM(CASE WHEN kind = 'ALLOCATION' THEN amount ELSE -amount END),0))::text AS amount FROM tesoreria.dues_allocations WHERE obligation_id = ${input.obligationId}`))[0]; if (!outstanding || input.amountCents > cents(outstanding.amount)) throw BusinessError(ErrorCode.CONFLICT, 'Allocation exceeds the obligation balance'); const allocated = rows<{amount:string}>(await db.execute(sql`SELECT COALESCE(SUM(amount),0)::text AS amount FROM tesoreria.dues_allocations WHERE settlement_id = ${input.settlementId} AND kind = 'ALLOCATION'`))[0]; if (cents(allocated?.amount ?? '0') + input.amountCents > cents(s.amount)) throw BusinessError(ErrorCode.CONFLICT, 'Allocations exceed the settlement amount') } const inserted = rows<Parameters<typeof allocation>[0]>(await db.execute(sql`INSERT INTO tesoreria.dues_allocations (settlement_id,obligation_id,kind,amount,compensates_allocation_id,reason) VALUES (${input.settlementId},${input.obligationId},${kind},${money(input.amountCents)},${input.compensatesAllocationId ?? null},${input.reason ?? null}) RETURNING ${allocationFields}`))[0]; if (!inserted) throw BusinessError(ErrorCode.INTERNAL_ERROR, 'Allocation insert returned no row'); return allocation(inserted) }
// prettier-ignore
export async function findAllocation(db:DuesDb, allocationId:string) { const row = rows<Parameters<typeof allocation>[0] & {socioId:string;settlementKind:SettlementKind;currency:string}>(await db.execute(sql`SELECT a.id,a.settlement_id AS "settlementId",a.obligation_id AS "obligationId",a.kind,a.amount::text,a.compensates_allocation_id AS "compensatesAllocationId",s.socio_id AS "socioId",s.kind AS "settlementKind",btrim(s.currency) AS currency FROM tesoreria.dues_allocations a JOIN tesoreria.dues_settlements s ON s.id = a.settlement_id WHERE a.id = ${allocationId}`))[0]; return row ? {...allocation(row),socioId:row.socioId,settlementKind:row.settlementKind,currency:row.currency} : null }
// prettier-ignore
export async function getDebt(db:DuesDb, socioId:string) { const result = await db.execute(sql`SELECT o.id,o.period_start AS "periodStart",o.period_end AS "periodEnd",o.amount::text,(o.amount - COALESCE(SUM(CASE WHEN a.kind = 'ALLOCATION' THEN a.amount ELSE -a.amount END),0))::text AS outstanding FROM tesoreria.dues_obligations o LEFT JOIN tesoreria.dues_allocations a ON a.obligation_id = o.id WHERE o.socio_id = ${socioId} AND o.kind = 'MONTHLY_DUES' GROUP BY o.id HAVING (o.amount - COALESCE(SUM(CASE WHEN a.kind = 'ALLOCATION' THEN a.amount ELSE -a.amount END),0)) > 0 ORDER BY o.period_start,o.id`); const obligations = rows<{id:string;periodStart:string;periodEnd:string;amount:string;outstanding:string}>(result).map(row => ({id:row.id,periodStart:row.periodStart,periodEnd:row.periodEnd,amountCents:cents(row.amount),outstandingCents:cents(row.outstanding)})); return {socioId,totalCents:obligations.reduce((total,item) => total + item.outstandingCents,0),obligations} }
