import { jobRuns, type Db, type JobRun, type NewJobRun } from '@athlos/db'
import { type SQL } from 'drizzle-orm'

/**
 * In-memory Drizzle standin for the scheduler tests. Mirrors the
 * shape of the @athlos/db insert/update/select surface the run-tracker
 * and the scheduler exercise. The standin is intentionally tiny —
 * it's a `Map<id, JobRun>` behind a Drizzle-shaped wrapper, enough to
 * drive the scheduler through happy paths + the boot reconciliation.
 *
 * Production code NEVER imports this — it's test-only. The real
 * Postgres driver is exercised in CI's Postgres service for full SQL
 * semantics.
 */

export type JobRunRow = JobRun

interface StandinState {
  rows: Map<string, JobRunRow>
}

export interface StandinDb {
  state: StandinState
  reset(): void
}

/**
 * SQL column name → JS row key. The standin stores rows in the
 * `$inferSelect` shape (camelCase) and the Drizzle query builder
 * references columns by their SQL name (snake_case). Every equality
 * check has to translate.
 */
const SQL_TO_JS: Record<string, string> = {
  id: 'id',
  job_name: 'jobName',
  scheduled_at: 'scheduledAt',
  started_at: 'startedAt',
  finished_at: 'finishedAt',
  status: 'status',
  attempt: 'attempt',
  error_message: 'errorMessage',
  metadata: 'metadata',
  triggered_by: 'triggeredBy',
}

function newId(): string {
  // Recognisable 36-char hex (matches UUID v4 shape; not generated by
  // a real v4 algorithm). Production uses `gen_random_uuid()` from
  // pgcrypto.
  return (
    '00000000-0000-4000-8000-' +
    Math.floor(Math.random() * 0xffffffff)
      .toString(16)
      .padStart(12, '0')
  )
}

function unwrap(v: unknown): unknown {
  if (v === null || v === undefined) return v
  if (typeof v !== 'object') return v
  const obj = v as { value?: unknown }
  if ('value' in obj) return obj.value
  return v
}

interface EqRef {
  sqlCol: string
  value: unknown
}

/**
 * Parse a Drizzle eq() leaf. Shape: 5 chunks, operator ` = ` at index 2.
 */
function parseEqLeaf(cond: unknown): EqRef | null {
  if (!cond || typeof cond !== 'object') return null
  const obj = cond as { queryChunks?: Array<unknown> }
  if (!obj.queryChunks || obj.queryChunks.length !== 5) return null
  const colChunk = obj.queryChunks[1] as { name?: string }
  const opChunk = obj.queryChunks[2] as { value?: string[] }
  const valChunk = obj.queryChunks[3]
  if (!colChunk || typeof colChunk.name !== 'string') return null
  if (!opChunk || !Array.isArray(opChunk.value) || opChunk.value[0] !== ' = ') {
    return null
  }
  return { sqlCol: colChunk.name, value: unwrap(valChunk) }
}

/**
 * Parse the `sql\`${col} = 'literal'\`` template form used by
 * reconcileOrphanedRuns. Shape: 3 chunks, the column ref at index 1
 * (with a placeholder chunk at index 0), the operator+literal at
 * index 2 as ` = 'literal'`.
 */
function parseSqlEqLeaf(cond: unknown): EqRef | null {
  if (!cond || typeof cond !== 'object') return null
  const obj = cond as { queryChunks?: Array<unknown> }
  if (!obj.queryChunks || obj.queryChunks.length !== 3) return null
  const colChunk = obj.queryChunks[1] as { name?: string }
  const valChunk = obj.queryChunks[2] as { value?: string[] | string }
  if (!colChunk || typeof colChunk.name !== 'string') return null
  const valueRaw = Array.isArray(valChunk.value) ? valChunk.value[0] : valChunk.value
  if (typeof valueRaw !== 'string') return null
  // The literal in the SQL template is wrapped in single quotes —
  // e.g. `status = 'running'` → value = " = 'running'". Strip the
  // operator + quotes.
  const m = valueRaw.match(/=\s*'([^']*)'/)
  if (!m || m[1] === undefined) return null
  return { sqlCol: colChunk.name, value: m[1] }
}

function rowGet(row: JobRunRow, sqlCol: string): unknown {
  const jsCol = SQL_TO_JS[sqlCol]
  if (!jsCol) return undefined
  return (row as unknown as Record<string, unknown>)[jsCol]
}

/**
 * Walk a Drizzle condition tree and collect every (sqlCol, value) pair
 * that should be ANDed. `and(eq(a,1), eq(b,2))` flattens to two pairs.
 *
 * Three shapes we recognise:
 *   1. `eq(col, val)`           — 5 chunks with ` = ` operator.
 *   2. `sql\`col = 'val'\``      — 3 chunks with `(` and `)` wrapping
 *                                  the column at index 1 and a single
 *                                  value chunk with ` = 'val'`.
 *   3. `and(a, b)`              — outer: 3 chunks with `(`, BuildSQL, `)`
 *                                  where the BuildSQL's own
 *                                  `queryChunks` is `[BuildSQL(a), ' and ', BuildSQL(b)]`.
 *                                  We recurse into each child.
 */
function flattenWhere(cond: unknown): EqRef[] {
  if (!cond) return []
  if (Array.isArray(cond)) return cond.flatMap(flattenWhere)
  if (typeof cond !== 'object') return []
  const obj = cond as { queryChunks?: Array<unknown> }
  if (!obj.queryChunks) return []
  // eq leaf or sql`...` leaf
  const eq = parseEqLeaf(cond) ?? parseSqlEqLeaf(cond)
  if (eq) return [eq]
  // sql`...` outer wrapper — 3 chunks with `(`, col, `)`. The
  // parseSqlEqLeaf above already handles the inner 3-chunk shape
  // produced by the template tag itself; this guards against
  // double-wrapping.
  // and(...) wrapper — outer 3 chunks with parens wrapping a BuildSQL.
  if (obj.queryChunks.length === 3) {
    const left = obj.queryChunks[0] as { value?: string[] }
    const right = obj.queryChunks[2] as { value?: string[] }
    if (
      left &&
      Array.isArray(left.value) &&
      left.value[0] === '(' &&
      right &&
      Array.isArray(right.value) &&
      right.value[0] === ')'
    ) {
      const mid = obj.queryChunks[1] as { queryChunks?: Array<unknown> }
      if (mid && Array.isArray(mid.queryChunks)) {
        // mid is the BuildSQL; recurse into its inner queryChunks
        // (which is the `[eq1, ' and ', eq2]` or similar shape).
        return mid.queryChunks.flatMap((c) => flattenWhere(c))
      }
    }
    // Direct and(a, b) shape (no parens wrapper): the middle chunk
    // is the ' and ' StringChunk. Recurse into the two sides.
    const mid = obj.queryChunks[1] as { value?: string[] }
    if (mid && Array.isArray(mid.value) && mid.value[0] === ' and ') {
      return [...flattenWhere(obj.queryChunks[0]), ...flattenWhere(obj.queryChunks[2])]
    }
  }
  return []
}

function matchesWhere(row: JobRunRow, cond: unknown): boolean {
  const refs = flattenWhere(cond)
  if (refs.length === 0) return true
  return refs.every((r) => rowGet(row, r.sqlCol) === r.value)
}

export function createStandinDb(): StandinDb {
  const state: StandinState = { rows: new Map() }
  return {
    state,
    reset() {
      state.rows.clear()
    },
  }
}

/**
 * Wrap a {@link StandinDb} as a Drizzle-shaped `Db`. Only the methods
 * the scheduler's run-tracker calls are implemented; the rest throw
 * at the type level (we cast at the boundary so callers see a `Db`).
 */
export function asDrizzle(standin: StandinDb): Db {
  return {
    insert: (_table: unknown) => ({
      values: (v: NewJobRun) => ({
        returning: () => {
          const id = newId()
          const row: JobRunRow = {
            id,
            jobName: v.jobName,
            scheduledAt: v.scheduledAt ?? new Date(),
            startedAt: v.startedAt ?? null,
            finishedAt: v.finishedAt ?? null,
            status: v.status ?? 'pending',
            attempt: v.attempt ?? 1,
            errorMessage: v.errorMessage ?? null,
            metadata: v.metadata ?? {},
            triggeredBy: v.triggeredBy ?? 'scheduler',
          }
          standin.state.rows.set(id, row)
          return Promise.resolve([row])
        },
      }),
    }),
    select: () => ({
      from: () => ({
        where: (cond: unknown) => {
          const matches = Array.from(standin.state.rows.values()).filter((r) =>
            matchesWhere(r, cond),
          )
          return Promise.resolve(matches)
        },
      }),
    }),
    update: (_table: unknown) => ({
      set: (patch: Partial<JobRunRow>) => {
        const apply = (cond: unknown): JobRunRow[] => {
          const refs = flattenWhere(cond)
          const updated: JobRunRow[] = []
          for (const r of standin.state.rows.values()) {
            const ok = refs.length === 0 || refs.every((x) => rowGet(r, x.sqlCol) === x.value)
            if (ok) {
              Object.assign(r, patch)
              updated.push(r)
            }
          }
          return updated
        }
        return {
          where: (cond: unknown) => ({
            returning: () => Promise.resolve(apply(cond)),
            then: (onFulfilled?: (v: JobRunRow[]) => unknown) =>
              Promise.resolve(apply(cond)).then(onFulfilled),
          }),
        }
      },
    }),
    delete: (_table: unknown) => ({
      where: (cond: unknown) => {
        const refs = flattenWhere(cond)
        const removed: JobRunRow[] = []
        for (const [id, r] of standin.state.rows) {
          const ok = refs.length === 0 || refs.every((x) => rowGet(r, x.sqlCol) === x.value)
          if (ok) {
            removed.push(r)
            standin.state.rows.delete(id)
          }
        }
        return Promise.resolve({ rowCount: removed.length })
      },
    }),
  } as unknown as Db
}

export type StandinJobRunsApi = ReturnType<typeof asDrizzle>

/** Re-export the schema constant for tests that want to reference it. */
export { jobRuns }

/** Convenience: return all rows in insertion order. */
export function listRows(standin: StandinDb): JobRunRow[] {
  return Array.from(standin.state.rows.values())
}

/** Convenience: find one row by id. */
export function findRow(standin: StandinDb, id: string): JobRunRow | undefined {
  return standin.state.rows.get(id)
}

/** Internal helper exposed for tests that need to seed a row. */
export function seedRow(standin: StandinDb, row: Partial<JobRunRow>): JobRunRow {
  const id = row.id ?? newId()
  const full: JobRunRow = {
    id,
    jobName: row.jobName ?? 'unknown',
    scheduledAt: row.scheduledAt ?? new Date(),
    startedAt: row.startedAt ?? null,
    finishedAt: row.finishedAt ?? null,
    status: row.status ?? 'pending',
    attempt: row.attempt ?? 1,
    errorMessage: row.errorMessage ?? null,
    metadata: row.metadata ?? {},
    triggeredBy: row.triggeredBy ?? 'scheduler',
  }
  standin.state.rows.set(id, full)
  return full
}

/**
 * Type marker so we can `import type { SQL } from ...` even when not
 * used in a particular test file (silences unused-import lints).
 */
export type _SQL = SQL
