-- The account chart is a seeded catalog only. Chart CRUD and general-ledger tables are deferred.
CREATE SCHEMA IF NOT EXISTS contabilidad;

CREATE TABLE IF NOT EXISTS contabilidad.plan_cuentas (
  code text PRIMARY KEY,
  name text NOT NULL,
  parent_code text,
  root_code text NOT NULL,
  active boolean NOT NULL,
  imputable boolean NOT NULL,
  CONSTRAINT plan_cuentas_parent_root_unique UNIQUE (code, root_code),
  CONSTRAINT plan_cuentas_parent_fk
    FOREIGN KEY (parent_code, root_code)
    REFERENCES contabilidad.plan_cuentas (code, root_code)
    ON DELETE RESTRICT,
  CONSTRAINT plan_cuentas_root_code_check CHECK (root_code IN ('1', '2', '3', '4', '5')),
  CONSTRAINT plan_cuentas_root_hierarchy_check CHECK (
    (parent_code IS NULL AND code = root_code AND NOT imputable)
    OR (parent_code IS NOT NULL AND code <> root_code)
  ),
  CONSTRAINT plan_cuentas_imputable_active_check CHECK (NOT imputable OR active)
);

INSERT INTO contabilidad.plan_cuentas (code, name, parent_code, root_code, active, imputable)
VALUES
  ('1', 'Activo', null, '1', true, false),
  ('1.1', 'Activo Corriente', '1', '1', true, false),
  ('1.1.1', 'Caja y Bancos', '1.1', '1', true, false),
  ('1.1.1.01', 'Caja (Pesos)', '1.1.1', '1', true, true),
  ('1.1.1.02', 'Caja Moneda Extranjera', '1.1.1', '1', true, true),
  ('1.1.1.03', 'Fondo Fijo (Caja Chica)', '1.1.1', '1', true, true),
  ('1.1.1.04', 'Banco X Cuenta Corriente', '1.1.1', '1', true, true),
  ('1.1.2', 'Inversiones', '1.1', '1', true, false),
  ('1.1.2.01', 'Plazo Fijo', '1.1.2', '1', true, true),
  ('1.1.2.02', 'Fondos Comunes de Inversión (FCI)', '1.1.2', '1', true, true),
  ('1.1.3', 'Créditos por Ventas', '1.1', '1', true, false),
  ('1.1.3.01', 'Deudores por Ventas', '1.1.3', '1', true, true),
  ('1.1.3.02', 'Valores a Depositar', '1.1.3', '1', true, true),
  ('1.1.3.03', 'Deudores Morosos', '1.1.3', '1', true, true),
  ('1.1.3.04', 'Tarjetas de Crédito a Cobrar', '1.1.3', '1', true, true),
  ('1.1.4', 'Otros Créditos', '1.1', '1', true, false),
  ('1.1.4.01', 'IVA Crédito Fiscal', '1.1.4', '1', true, true),
  ('1.1.4.02', 'Retenciones/Percepciones sufridas (IVA, Ingresos Brutos, Ganancias)', '1.1.4', '1', true, true),
  ('1.1.4.03', 'Anticipos a Proveedores', '1.1.4', '1', true, true),
  ('1.1.5', 'Bienes de Cambio', '1.1', '1', true, false),
  ('1.1.5.01', 'Mercaderías', '1.1.5', '1', true, true),
  ('1.1.5.02', 'Materias Primas', '1.1.5', '1', true, true),
  ('1.2', 'Activo No Corriente', '1', '1', true, false),
  ('1.2.1', 'Bienes de Uso', '1.2', '1', true, false),
  ('1.2.1.01', 'Inmuebles', '1.2.1', '1', true, true),
  ('1.2.1.02', 'Rodados', '1.2.1', '1', true, true),
  ('1.2.1.03', 'Muebles y Útiles', '1.2.1', '1', true, true),
  ('1.2.1.04', 'Instalaciones', '1.2.1', '1', true, true),
  ('1.2.1.05', 'Equipos de Computación', '1.2.1', '1', true, true),
  ('1.2.1.06', 'Depreciación Acumulada - Inmuebles', '1.2.1', '1', true, true),
  ('1.2.1.07', 'Depreciación Acumulada - Rodados', '1.2.1', '1', true, true),
  ('1.2.1.08', 'Depreciación Acumulada - Muebles y Útiles', '1.2.1', '1', true, true),
  ('1.2.1.09', 'Depreciación Acumulada - Instalaciones', '1.2.1', '1', true, true),
  ('1.2.1.10', 'Depreciación Acumulada - Equipos de Computación', '1.2.1', '1', true, true),
  ('2', 'Pasivo', null, '2', true, false),
  ('2.1', 'Pasivo Corriente', '2', '2', true, false),
  ('2.1.1', 'Deudas Comerciales', '2.1', '2', true, false),
  ('2.1.1.01', 'Proveedores', '2.1.1', '2', true, true),
  ('2.1.1.02', 'Acreedores Varios', '2.1.1', '2', true, true),
  ('2.1.1.03', 'Cheques de Pago Diferido Entregados', '2.1.1', '2', true, true),
  ('2.1.2', 'Préstamos', '2.1', '2', true, false),
  ('2.1.2.01', 'Adelantos en Cuenta Corriente', '2.1.2', '2', true, true),
  ('2.1.2.02', 'Préstamos Bancarios a pagar', '2.1.2', '2', true, true),
  ('2.1.3', 'Remuneraciones y Cargas Sociales', '2.1', '2', true, false),
  ('2.1.3.01', 'Sueldos a Pagar', '2.1.3', '2', true, true),
  ('2.1.3.02', 'Cargas Sociales a Pagar (AFIP, Sindicatos, Obra Social)', '2.1.3', '2', true, true),
  ('2.1.3.03', 'Provisión para SAC y Vacaciones', '2.1.3', '2', true, true),
  ('2.1.4', 'Cargas Fiscales', '2.1', '2', true, false),
  ('2.1.4.01', 'IVA Débito Fiscal', '2.1.4', '2', true, true),
  ('2.1.4.02', 'IVA Saldo a Pagar', '2.1.4', '2', true, true),
  ('2.1.4.03', 'Ingresos Brutos a Pagar', '2.1.4', '2', true, true),
  ('2.1.4.04', 'Provisión Impuesto a las Ganancias', '2.1.4', '2', true, true),
  ('2.1.4.05', 'Moratorias AFIP', '2.1.4', '2', true, true),
  ('2.2', 'Pasivo No Corriente', '2', '2', true, false),
  ('2.2.1', 'Deudas a Largo Plazo', '2.2', '2', true, false),
  ('2.2.1.01', 'Préstamos Bancarios (cuotas con vencimiento a más de un año)', '2.2.1', '2', true, true),
  ('3', 'Patrimonio Neto', null, '3', true, false),
  ('3.1', 'Capital', '3', '3', true, false),
  ('3.1.01', 'Capital Social', '3.1', '3', true, true),
  ('3.1.02', 'Aportes Irrevocables', '3.1', '3', true, true),
  ('3.2', 'Resultados Acumulados', '3', '3', true, false),
  ('3.2.01', 'Reserva Legal', '3.2', '3', true, true),
  ('3.2.02', 'Resultados No Asignados', '3.2', '3', true, true),
  ('3.2.03', 'Resultado del Ejercicio', '3.2', '3', true, true),
  ('4', 'Ingresos', null, '4', true, false),
  ('4.1', 'Ingresos Operativos', '4', '4', true, false),
  ('4.1.01', 'Cuotas sociales', '4.1', '4', true, true),
  ('4.1.02', 'Ventas de Mercaderías', '4.1', '4', true, true),
  ('4.1.03', 'Ventas de Servicios', '4.1', '4', true, true),
  ('4.2', 'Otros Ingresos', '4', '4', true, false),
  ('4.2.01', 'Intereses Ganados', '4.2', '4', true, true),
  ('4.2.02', 'Diferencias de Cambio (positivas)', '4.2', '4', true, true),
  ('4.2.03', 'Descuentos Obtenidos', '4.2', '4', true, true),
  ('5', 'Egresos', null, '5', true, false),
  ('5.1', 'Costos Operativos', '5', '5', true, false),
  ('5.1.01', 'Costo de Mercaderías Vendidas (CMV)', '5.1', '5', true, true),
  ('5.2', 'Gastos de Administración y Comercialización', '5', '5', true, false),
  ('5.2.01', 'Sueldos y Jornales', '5.2', '5', true, true),
  ('5.2.02', 'Cargas Sociales', '5.2', '5', true, true),
  ('5.2.03', 'Alquileres Perdidos', '5.2', '5', true, true),
  ('5.2.04', 'Servicios (Luz, Agua, Internet)', '5.2', '5', true, true),
  ('5.2.05', 'Honorarios Profesionales', '5.2', '5', true, true),
  ('5.2.06', 'Seguros', '5.2', '5', true, true),
  ('5.2.07', 'Movilidad y Viáticos', '5.2', '5', true, true),
  ('5.2.08', 'Papelería y Útiles', '5.2', '5', true, true),
  ('5.2.09', 'Impuestos y Tasas (Municipales/Provinciales)', '5.2', '5', true, true),
  ('5.3', 'Gastos Financieros', '5', '5', true, false),
  ('5.3.01', 'Intereses Perdidos', '5.3', '5', true, true),
  ('5.3.02', 'Gastos y Comisiones Bancarias', '5.3', '5', true, true),
  ('5.3.03', 'Diferencias de Cambio (negativas)', '5.3', '5', true, true),
  ('5.3.04', 'Impuesto a los Débitos y Créditos Bancarios (Ley 25.413)', '5.3', '5', true, true),
  ('5.4', 'Depreciaciones', '5', '5', true, false),
  ('5.4.01', 'Amortización / Depreciación Bienes de Uso', '5.4', '5', true, true)
ON CONFLICT (code) DO NOTHING;
